os: linux
dist: bionic
language: java
jdk: openjdk11
cache:
  directories:
  - "$HOME/.m2"
addons:
  sonarcloud:
    organization: molgenis
    token:
      secure: "XuiZEuAlMLTNhw7FdZAEyRInmk2+X+oLxNp6ojtATNbdIwU2ZqWuYb8sqHDvlM9cCewDy1719CCaYOApOVhKIHzDVRieYHcvLR4Tc9eKAIGM1DEE+1P3vgT71vbCS1yFSp2UPN5+u/us66vx9O+deuGRAxcf1X5dpHDuG0R1/3SMAoCx8Reymd3qSZ7BzrKih4pYlAMb45zaduoZA54xuAt+fJgORuuB9DMDQRXQWIKUGkaVq9zf1G+w9iWdJ009jUFsqFA9iF1P7RIDaNlyPUBe1DhOSKqZVmI60yQ9VDcGuKnesyL17ZXfYYCBLmk9N/zA9FEUCZAqHHM2ikNij5tRwIon3zIPc3DrZBk0f8nFyPOd2QiaG+KMNo+gSZeC2JBE6CFfqyiYHzsUeg73SbD5g6QWWFdmdzT1/m2cSD2JFknnVOc+6HIvyjforc2N8myi8pb6zYO33Syco5piKmHozrKp0wFUCrQSOLyuYzIsebHogJPdUPuw97a5xzS2jo84TQe2lH+k7Bc6NV2QZD7xXUiBBDTlxPIwFg4Q4YdvJxIOSZ1PW2z/4EPEz25mGmdtQAtac0BYYdQcG2h2PGfcgoVjlM8sP8bEGhi/83zWYJkwIxrHMtH2xG7nvk2k7XzFYa4jQqBwcp3rgTfYKHFty6i20q7dUa7OgG2wIgQ="
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=molgenis_vip-report
